# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0002_invite_max_guests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='meal',
        ),
        migrations.AddField(
            model_name='guest',
            name='type',
            field=models.CharField(choices=[(b'adult', b'Adult'), (b'child', b'Child')], default=b'adult', max_length=16),
        ),
        migrations.DeleteModel(
            name='Meal',
        ),
    ]
