# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 01:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0004_story'),
        ('rsvp', '0003_auto_20170108_1708'),
    ]

    operations = [
    ]
