# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-21 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0005_merge_20170108_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_family', models.CharField(max_length=32)),
                ('font_class', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='guest',
            name='name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='story',
            name='icon',
            field=models.ForeignKey(null=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='rsvp.Icon'),
            preserve_default=False,
        ),
    ]
